/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_demo;

import static database_demo.methodClass.Patient_ID;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mackansari
 */
public class NewPatient_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewPatient_GUI
     */
    public NewPatient_GUI() {
        initComponents();
    }
    
    public Connection getConnection()
    {
        Connection con = null;
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost3306/demo","root", "Ma@151786");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
                return con;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("demo?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        personQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Person p");
        personList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : personQuery.getResultList();
        personQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Person p");
        personList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : personQuery1.getResultList();
        patListQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM PatList p");
        patListList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : patListQuery.getResultList();
        home_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        textField4 = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        textField9 = new java.awt.TextField();
        textField10 = new java.awt.TextField();
        textField11 = new java.awt.TextField();
        textField12 = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        textField14 = new java.awt.TextField();
        textField15 = new java.awt.TextField();
        textField16 = new java.awt.TextField();
        textField17 = new java.awt.TextField();
        jLabel18 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JText_Search = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        textField7 = new java.awt.TextField();
        textField8 = new java.awt.TextField();
        textField13 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        home_panel.setBackground(new java.awt.Color(176, 196, 222));
        home_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sacred_transparent.png"))); // NOI18N
        home_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 840, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, patListList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patientID}"));
        columnBinding.setColumnName("Patient ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patFName}"));
        columnBinding.setColumnName("Pat FName");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patMName}"));
        columnBinding.setColumnName("Pat MName");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patLName}"));
        columnBinding.setColumnName("Pat LName");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patPriority}"));
        columnBinding.setColumnName("Pat Priority");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patDOB}"));
        columnBinding.setColumnName("Pat DOB");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patWeight}"));
        columnBinding.setColumnName("Pat Weight");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patHeight}"));
        columnBinding.setColumnName("Pat Height");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patStreetAddrs}"));
        columnBinding.setColumnName("Pat Street Addrs");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patState}"));
        columnBinding.setColumnName("Pat State");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patCity}"));
        columnBinding.setColumnName("Pat City");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patComments}"));
        columnBinding.setColumnName("Pat Comments");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        home_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1000, 340));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton5.setLabel("Add Patients");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        home_panel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search1.png"))); // NOI18N
        jButton6.setLabel("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        home_panel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 140, -1));

        getContentPane().add(home_panel, "card2");

        addPanel.setBackground(new java.awt.Color(176, 196, 222));
        addPanel.setName(""); // NOI18N
        addPanel.setPreferredSize(new java.awt.Dimension(847, 462));
        addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.png"))); // NOI18N
        jButton1.setLabel("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        addPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 60));

        jLabel2.setText("First Name");
        addPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, -1));

        jLabel3.setText("Middle Name");
        addPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 120, 30));

        jLabel4.setText("Last Name ");
        addPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 130, 30));

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        addPanel.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 160, 30));
        addPanel.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 160, 30));
        addPanel.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 160, 30));

        jLabel5.setText("Date of Birth");
        addPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setText("Height (e.g. 5\" 3')");
        addPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel7.setText("Weight (lbs.)");
        addPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));
        addPanel.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 160, 30));

        textField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField4ActionPerformed(evt);
            }
        });
        addPanel.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 160, 30));

        jLabel8.setText("Priority ");
        addPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 20));

        jLabel9.setText("City ");
        addPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 120, 20));

        jLabel10.setText("State");
        addPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        addPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 200, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Very High", "High", "Medium", "Low" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        addPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        textField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField9ActionPerformed(evt);
            }
        });
        addPanel.add(textField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 160, 30));
        addPanel.add(textField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 160, 30));

        textField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField11ActionPerformed(evt);
            }
        });
        addPanel.add(textField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 160, 30));
        addPanel.add(textField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 30));

        jLabel11.setText("Street");
        addPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 140, 20));
        addPanel.add(textField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 30));

        textField15.setText("textField15");
        addPanel.add(textField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 140, 40));

        textField16.setText("textField16");
        addPanel.add(textField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 130, 30));
        addPanel.add(textField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 30));
        addPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 160, 30));

        getContentPane().add(addPanel, "card3");
        addPanel.getAccessibleContext().setAccessibleDescription("");

        searchPanel.setBackground(new java.awt.Color(176, 196, 222));
        searchPanel.setPreferredSize(new java.awt.Dimension(847, 462));
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.png"))); // NOI18N
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 60));

        jLabel12.setText("     Patient Search");
        searchPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 130, 40));

        jLabel13.setText("Search Something");
        searchPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel14.setText("Last Name");
        searchPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel15.setText("Date of Birth");
        searchPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel16.setText("    OR");
        searchPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel17.setText("Patient ID");
        searchPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        searchPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, patListList, jTable2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patCity}"));
        columnBinding.setColumnName("Pat City");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patComments}"));
        columnBinding.setColumnName("Pat Comments");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patDOB}"));
        columnBinding.setColumnName("Pat DOB");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patFName}"));
        columnBinding.setColumnName("Pat FName");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patHeight}"));
        columnBinding.setColumnName("Pat Height");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patLName}"));
        columnBinding.setColumnName("Pat LName");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patMName}"));
        columnBinding.setColumnName("Pat MName");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patPriority}"));
        columnBinding.setColumnName("Pat Priority");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patState}"));
        columnBinding.setColumnName("Pat State");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patStreetAddrs}"));
        columnBinding.setColumnName("Pat Street Addrs");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patWeight}"));
        columnBinding.setColumnName("Pat Weight");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${patientID}"));
        columnBinding.setColumnName("Patient ID");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(jTable2);

        searchPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 820, 250));

        JText_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JText_SearchActionPerformed(evt);
            }
        });
        searchPanel.add(JText_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 160, 30));
        searchPanel.add(textField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 140, 20));
        searchPanel.add(textField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 140, -1));
        searchPanel.add(textField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 140, -1));

        textField13.setText("textField13");
        searchPanel.add(textField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, 20));

        getContentPane().add(searchPanel, "card4");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        home_panel.setVisible(true);
        addPanel.setVisible(false);
        getConnection();
        SwingUtilities.updateComponentTreeUI(jTable1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        home_panel.setVisible(true);
        searchPanel.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField4ActionPerformed

    private void JText_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JText_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JText_SearchActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        final String Pat_FName = textField1.getText();
        final String Pat_MName = textField2.getText();
        final String Pat_LName = textField3.getText();
        final String Pat_DOB =  "";//textField14.getText();
        final String Pat_Weight = textField4.getText();
        final String Pat_Height =  textField11.getText();
        final String Pat_StreetAddrs = textField12.getText();
        final String Pat_City = textField9.getText();
        final String Pat_State = textField10.getText();
        final String Pat_Priority =  textField17.getText(); //jComboBox1.getActionCommand();
        final String Pat_Comments =  ""; //textField15.getText();
        boolean success = false;
				try {
					methodClass.addEntry(Pat_FName, Pat_LName, Pat_MName, Pat_StreetAddrs, Pat_City, Pat_State, Pat_Height, Pat_Weight, Pat_DOB,Pat_Priority, Pat_Comments);
					success = true;
				} catch (Exception e1) {
					e1.printStackTrace();
				}
				
				if(success){
                                         
					JOptionPane.showMessageDialog(getContentPane(),"Entry Added!");
				} 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField11ActionPerformed

    private void textField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        addPanel.setVisible(true);
        home_panel.setVisible(false);        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        searchPanel.setVisible(true);
        home_panel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPatient_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPatient_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPatient_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPatient_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPatient_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField JText_Search;
    private javax.swing.JPanel addPanel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel home_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.util.List<database_demo.PatList> patListList;
    private javax.persistence.Query patListQuery;
    private java.util.List<database_demo.Person> personList;
    private java.util.List<database_demo.Person> personList1;
    private javax.persistence.Query personQuery;
    private javax.persistence.Query personQuery1;
    private javax.swing.JPanel searchPanel;
    private java.awt.TextField textField1;
    private java.awt.TextField textField10;
    private java.awt.TextField textField11;
    private java.awt.TextField textField12;
    private java.awt.TextField textField13;
    private java.awt.TextField textField14;
    private java.awt.TextField textField15;
    private java.awt.TextField textField16;
    private java.awt.TextField textField17;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    private java.awt.TextField textField9;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
                        }

